name: Build-Test-Push
on:
  push:

jobs:
  build-test-push:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby: ["3.0.4"]
        ubuntu: ["focal"]
        arch: ["linux/amd64", "linux/arm64"]
        include:
          - ruby: "3.0.4"
            ruby_checksum: "70b47c207af04bce9acea262308fb42893d3e244f39a4abc586920a1c723722b"

    steps:
      - uses: actions/checkout@v3
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        name: Build
        with:
          platforms: ${{ matrix.arch }}
          push: false
          load: true
          build-args: |
            RUBY_VERSION:${{ matrix.ruby }}
            RUBY_CHECKSUM:${{ matrix.ruby_checksum }}
            UBUNTU_VERSION:${{ matrix.ubuntu }}
          tags: "ruby-jemalloc"
      - uses: e1himself/goss-installation-action@v1.0.4
        name: Install goss/dgoss
      - name: Test
        run: dgoss run -ti -e RUBY_VERSION=${{ matrix.ruby }} ruby-jemalloc
      - name: Push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: ${{ matrix.arch }}
          tags: "ghcr.io/moritzheiber/ruby-jemalloc-${{ matrix.ubuntu }}-${{ matrix.ruby }}"
